#!/usr/bin/fish

#Dependencies for the rest of the script: git and curl
if not type -q git
    sudo pacman -S base-devel git
end

if not type -q curl
    sudo pacman -S curl
end

#Tmux install
if not type -q tmux
    sudo pacman -S tmux
end

if not type -q nvim
    sudo pacman -S neovim
end

if not test -d "~/.tmux/plugins/tpm"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
end

if not test -d "~/.local/share/nvim/site/pack/packer/"
    echo "bootrapping packer"
    git clone --depth 1 https://github.com/wbthomason/packer.nvim \
        ~/.local/share/nvim/site/pack/packer/start/packer.nvim
end

nvim "+PackerSync" "+qall"

#GDB Dashboard
wget -P ~ https://git.io/.gdbinit

#Fisher plugin manager
if not type -q fisher
    curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
    fisher install patrickf1/fzf.fish
    fisher install edc/bass
end

#Starship prompt
if not type -q starship
    curl -sS https://starship.rs/install.sh | sh
end
