#!/bin/bash

#Dependencies for the rest of the script: git and curl
if ! command -v git > /dev/null 2>&1; then
    sudo pacman -S base-devel git
fi

if ! command -v curl > /dev/null 2>&1; then
    sudo pacman -S curl
fi

#Tmux install
if ! command -v tmux > /dev/null 2>&1; then
    sudo pacmand -S tmux
fi

if ! command -v nvim > /dev/null 2>&1; then
    sudo pacman -S neovim
fi

if [ ! -d "$HOME/.tmux/plugins/tpm" ]
then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [ ! -d "$HOME/.local/share/nvim/site/pack/packer/" ]
then
    echo "bootrapping packer"
    git clone --depth 1 https://github.com/wbthomason/packer.nvim \
        ~/.local/share/nvim/site/pack/packer/start/packer.nvim
fi

nvim "+PackerSync" "+qall"

#GDB Dashboard
wget -P ~ https://git.io/.gdbinit

#Fisher plugin manager
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fisher install patrickf1/fzf.fish
fisher install edc/bass

#Starship prompt
curl -sS https://starship.rs/install.sh | sh
